version: 2
jobs:
  validate:
    docker:
      image: node:10
    steps:
      - checkout
      - run: 
        name: Starting
        command: echo "Starting circleCI"
      - run:
        name: Install dependencies
        command: npm install
      - run: 
        name: Execute NodeJS
        command: node index.js

  restart-compose:
    docker:
      image: node/latest 
    steps:
      - checkout
      - run: echo "Restarting compose service"
      - run: node -v

workflows:
  version: 2
  build-application:
    jobs:
      - validate
      - restart-compose:
          requires:
            - validate
