version: 2.1
# orbs:
#   node: circleci/node@1.1
jobs:
  build:
    docker:
      image: circleci/node@2.0.2
    steps:
      - checkout
      - run: echo "Hello CircleCI"
      # - node/with-cache:
      #     steps:
      #       - run: npm install
      - run: npm install
      - run: node index.js
  restart-compose:
    docker:
      name: node/latest 
    steps:
      - run: echo "Restart compose service"
      - run: node -v

workflows:
  version: 2.1
  all:
    jobs:
      - build
      - restart-compose:
        requires:
          - build
